#!/usr/bin/env python3
"""Builds the embedded PMI brand fonts.

Reads the licensed font files from `PMI branding guidelines/Fonts/` (kept out of git), subsets
each cut to the Latin ranges this app needs, and writes the same base64 WOFF2 data to:
  - js/custom-fonts.js  (embedded in every export, so a block renders in the brand fonts anywhere)
  - fonts.css           (the builder app shell)

Requires: pip install fonttools brotli
Usage:    python scripts/build-pmi-fonts.py

Licensing: Aeonik and GT Pressura Mono are commercial fonts (CoType Foundry). Their web-font
terms restrict use to one domain and prohibit making the files available to third parties.
Embedding them in exported learning content, and committing the generated data, was done on the
project owner's confirmation that PMI permits it. Anyone reusing this repository must
independently reconfirm that permission.
"""
import base64
import io
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "PMI branding guidelines" / "Fonts"

# (family, weight, style, source file)
FACES = [
    ("Aeonik", 400, "normal", FONTS / "Aeonik" / "Aeonik-Regular.woff2"),
    ("Aeonik", 400, "italic", FONTS / "Aeonik" / "Aeonik-RegularItalic.woff2"),
    ("Aeonik", 500, "normal", FONTS / "Aeonik" / "Aeonik-Medium.woff2"),
    ("Aeonik", 700, "normal", FONTS / "Aeonik" / "Aeonik-Bold.woff2"),
    ("Aeonik", 700, "italic", FONTS / "Aeonik" / "Aeonik-BoldItalic.woff2"),
    ("GT Pressura Mono", 400, "normal", FONTS / "GT-Pressura" / "GT-Pressura-Mono-Regular.otf"),
    ("GT Pressura Mono", 700, "normal", FONTS / "GT-Pressura" / "GT-Pressura-Mono-Bold.woff2"),
]

# Basic Latin, Latin-1, Latin Extended-A, general punctuation, currency, trademark, arrows, minus.
UNICODES = (
    list(range(0x0020, 0x007F)) + list(range(0x00A0, 0x0100)) + list(range(0x0100, 0x0180))
    + list(range(0x2000, 0x2070)) + list(range(0x20A0, 0x20C0))
    + [0x2122, 0x2190, 0x2191, 0x2192, 0x2193, 0x2212, 0x2022, 0x25CF]
)


def subset_to_woff2(path: Path) -> bytes:
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["kern", "liga", "calt", "ccmp", "locl", "mark", "mkmk", "case", "tnum", "lnum"]
    options.name_IDs = [1, 2, 3, 4, 6]
    options.notdef_outline = True
    options.hinting = False
    font = TTFont(str(path))
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=UNICODES)
    subsetter.subset(font)
    out = io.BytesIO()
    font.flavor = "woff2"
    font.save(out)
    return out.getvalue()


def font_face(family: str, weight: int, style: str, data: bytes) -> str:
    b64 = base64.b64encode(data).decode("ascii")
    return (
        "@font-face {\n"
        f"  font-family: '{family}';\n"
        f"  font-weight: {weight};\n"
        f"  font-style: {style};\n"
        "  font-display: swap;\n"
        f"  src: url(data:font/woff2;base64,{b64}) format('woff2');\n"
        "}"
    )


def main() -> int:
    missing = [str(f[3]) for f in FACES if not f[3].exists()]
    if missing:
        print("Missing font files (the licensed fonts are kept out of git):\n  " + "\n  ".join(missing), file=sys.stderr)
        return 1

    faces = []
    total = 0
    for family, weight, style, path in FACES:
        data = subset_to_woff2(path)
        total += len(data)
        print(f"  {family} {weight} {style}: {len(data):,} bytes (from {path.name})")
        faces.append((family, weight, style, font_face(family, weight, style, data)))
    print(f"Total WOFF2: {total:,} bytes; base64 about {int(total * 4 / 3):,} bytes")

    aeonik = "\n\n".join(f[3] for f in faces if f[0] == "Aeonik")
    mono = "\n\n".join(f[3] for f in faces if f[0] == "GT Pressura Mono")

    header = """// PMI brand fonts, embedded as base64 WOFF2 so they travel with every export mode identically
// (Web Package ZIP, HTML fragment, course ZIP) with no external dependency and no separate asset
// step, matching the single-compiler guarantee (docs/EXPORT-CONTRACT.md).
//
//   Aeonik            primary   — headlines, page titles, body (400, 400 italic, 500, 700, 700 italic)
//   GT Pressura Mono  secondary — subtitles, captions, footers (400, 700)
//
// GENERATED by scripts/build-pmi-fonts.py from the licensed files in
// `PMI branding guidelines/Fonts/`. Do not edit by hand; re-run the script instead.
// Each cut is subset to Latin (Basic Latin, Latin-1, Latin Extended-A, general punctuation,
// currency, trademark, arrows, minus) — see the script for the exact ranges.
//
// LICENSING: these are commercial CoType Foundry fonts. Their web-font terms restrict use to
// one domain and bar making the files available to third parties. Embedding them in exported
// content, and committing this generated file, was done on the project owner's confirmation
// that PMI permits it. Anyone reusing this repository must reconfirm that permission.

"""
    js = (
        header
        + "export const AEONIK_FONT_FAMILY = 'Aeonik';\n"
        + "export const GT_PRESSURA_MONO_FONT_FAMILY = 'GT Pressura Mono';\n\n"
        + "export const AEONIK_FONT_FACE_CSS = `" + aeonik + "`;\n\n"
        + "export const GT_PRESSURA_MONO_FONT_FACE_CSS = `" + mono + "`;\n\n"
        + "// Lookup by font-family name — every self-hosted font this project embeds is registered here so\n"
        + "// js/preview.js and js/export-shell.js can tell a self-hosted family apart from a Google Fonts\n"
        + "// one without a component-by-component special case.\n"
        + "export const CUSTOM_FONT_FACES_BY_FAMILY = Object.freeze({\n"
        + "  [AEONIK_FONT_FAMILY]: AEONIK_FONT_FACE_CSS,\n"
        + "  [GT_PRESSURA_MONO_FONT_FAMILY]: GT_PRESSURA_MONO_FONT_FACE_CSS\n"
        + "});\n"
    )
    (ROOT / "js" / "custom-fonts.js").write_text(js, encoding="utf-8", newline="\n")

    css = (
        "/* PMI brand fonts for the builder app shell — GENERATED by scripts/build-pmi-fonts.py.\n"
        "   Same data as js/custom-fonts.js (used for exported output). See that file's header for\n"
        "   the licensing note. Do not edit by hand. */\n\n"
        + aeonik + "\n\n" + mono + "\n"
    )
    (ROOT / "fonts.css").write_text(css, encoding="utf-8", newline="\n")
    print("Wrote js/custom-fonts.js and fonts.css")
    return 0


if __name__ == "__main__":
    sys.exit(main())
