import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';

import { AUDIO_PLAYER_SAMPLES, buildSampleProject } from '../fixtures/audio-player-sample-definitions.mjs';
import * as audioPlayer from '../../components/audio-player.js';
import { collectSyncIssues } from '../../js/validation.js';
import { validateProject } from '../../js/storage.js';

// Drift detector: docs/examples/audio-player/*.json are committed files, generated by
// scripts/generate-audio-player-samples.mjs, referenced from docs/AUDIO-PLAYER.md as an
// importable sample project. If someone changes the audio-player schema/defaultConfig and
// forgets to regenerate the sample, this test fails loudly instead of a stale, possibly
// now-invalid sample silently sitting in the repo — same reasoning
// tests/unit/interactive-video-samples.test.js already established.
const samplesDir = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'docs', 'examples', 'audio-player');

describe('Audio Player sample project is in sync with the current schema', () => {
  test.each(AUDIO_PLAYER_SAMPLES)('$filename matches a fresh build, aside from its own updatedAt timestamp', async ({ filename, ...sample }) => {
    const committed = JSON.parse(await readFile(join(samplesDir, filename), 'utf8'));
    const fresh = buildSampleProject({ filename, ...sample });
    const { updatedAt: _committedUpdatedAt, ...committedRest } = committed;
    const { updatedAt: _freshUpdatedAt, ...freshRest } = fresh;
    expect(committedRest, `docs/examples/audio-player/${filename} is stale — run "node scripts/generate-audio-player-samples.mjs" and commit the result`).toEqual(freshRest);
  });
});

describe('Audio Player sample project is genuinely valid, importable, and demonstrates the documented feature set', () => {
  test.each(AUDIO_PLAYER_SAMPLES)('$filename passes validateProject(), the component\'s own validate(), and has zero blocking Preflight issues', async ({ filename }) => {
    const raw = JSON.parse(await readFile(join(samplesDir, filename), 'utf8'));
    const result = validateProject(raw);
    expect(result.valid, result.valid ? '' : result.error).toBe(true);

    const componentResult = audioPlayer.validate(result.project.config);
    expect(componentResult.valid, JSON.stringify(componentResult.errors)).toBe(true);

    const issues = collectSyncIssues({
      componentId: 'audio-player',
      schema: audioPlayer.editorSchema,
      config: result.project.config,
      theme: result.project.theme,
      componentOverrides: result.project.componentOverrides,
      settings: {}
    });
    const blocking = issues.filter(issue => issue.severity === 'blocking');
    expect(blocking, JSON.stringify(blocking.map(issue => issue.explanation))).toEqual([]);
  });

  test('podcast-episode.json demonstrates podcast mode, 4+ chapters, a synchronized transcript, resume/progress, and reveal-after-completion takeaways', async () => {
    const raw = JSON.parse(await readFile(join(samplesDir, 'podcast-episode.json'), 'utf8'));
    const { config } = raw;
    expect(config.presentationMode).toBe('podcast');
    expect(audioPlayer.parseChapters(config.chapters).length).toBeGreaterThanOrEqual(4);
    expect(audioPlayer.parseTranscriptSegments(config.transcriptSegments).length).toBeGreaterThan(0);
    expect(config.progressPersistence).toBe(true);
    expect(config.takeawaysVisibility).toBe('afterCompletion');
    expect(audioPlayer.parseTakeaways(config.takeaways).length).toBeGreaterThan(0);
  });
});
