import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';

import { compileExportFixture, EXPORT_FIXTURES } from '../fixtures/export-fixture-definitions.mjs';

// Drift detector: tests/fixtures/exports/*.html are committed files, generated by
// scripts/generate-export-fixtures.mjs, that back both a manual test-page index
// (tests/fixtures/exports/index.html) and the automated tests/e2e/exported-fixtures.spec.js.
// If someone changes a component's generateHTML/generateCSS/generateJS and forgets to
// regenerate the fixture, this test fails loudly instead of the fixture silently going
// stale (still "passing" its own e2e checks, just not representing current output).
const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'fixtures', 'exports');

describe('export fixtures are in sync with the current export pipeline', () => {
  test.each(EXPORT_FIXTURES)('$filename matches a fresh compile of $componentId', async ({ componentId, filename }) => {
    const committed = await readFile(join(fixturesDir, filename), 'utf8');
    const fresh = compileExportFixture(componentId);
    expect(committed, `tests/fixtures/exports/${filename} is stale — run "npm run fixtures:exports" and commit the result`).toBe(fresh);
  });
});

// P04: WOFF2 + subsetting cut every export's embedded-font cost from ~270 KB (5 TTF
// weights) to ~98 KB (raw) / ~150 KB total compiled HTML for a typical component — this
// guards that regression from silently creeping back in (e.g. someone re-embedding a TTF
// fallback "for safety," or duplicating a font weight).
describe('embedded font stays WOFF2, not TTF, and export size stays optimized', () => {
  test.each(EXPORT_FIXTURES)('$filename embeds exactly 6 WOFF2 font-face declarations, no TTF', ({ componentId, filename }) => {
    const html = compileExportFixture(componentId);
    const woff2Matches = html.match(/data:font\/woff2;base64,/g) || [];
    expect(woff2Matches, `${filename} should embed exactly 6 faces (Aeonik Regular/Italic/Medium/Bold, GT Pressura Mono Regular/Bold)`).toHaveLength(6);
    expect(html).not.toContain('data:font/ttf');
    expect(html).not.toContain("format('truetype')");
  });

  test.each(EXPORT_FIXTURES)('$filename compiles to well under the pre-P04 unoptimized baseline (~377 KB)', ({ componentId, filename }) => {
    const html = compileExportFixture(componentId);
    const bytes = new Blob([html]).size;
    // Ceiling (240 KB): above every current fixture (~167–205 KB with the six embedded PMI faces)
    // so ordinary content growth doesn't make this flaky, while still catching a regression such as
    // embedding uncompressed TTFs or the full, unsubsetted fonts (each face is ~15 KB subset).
    expect(bytes, `${filename} is ${bytes} bytes — investigate before raising this ceiling`).toBeLessThan(240 * 1024);
  });
});
