import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';

import { buildSampleProject, INTERACTIVE_VIDEO_SAMPLES } from '../fixtures/interactive-video-sample-definitions.mjs';
import * as interactiveVideo from '../../components/interactive-video.js';
import { collectSyncIssues } from '../../js/validation.js';
import { validateProject } from '../../js/storage.js';

// Drift detector: docs/examples/interactive-video/*.json are committed files, generated by
// scripts/generate-interactive-video-samples.mjs, referenced from docs/INTERACTIVE-VIDEO.md
// as importable sample projects. If someone changes the interactive-video schema/defaultConfig
// and forgets to regenerate the samples, this test fails loudly instead of a stale, possibly
// now-invalid sample silently sitting in the repo — same reasoning
// tests/unit/export-fixtures.test.js already established for export fixtures.
const samplesDir = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'docs', 'examples', 'interactive-video');

describe('Interactive Video sample projects are in sync with the current schema', () => {
  test.each(INTERACTIVE_VIDEO_SAMPLES)('$filename matches a fresh build, aside from its own updatedAt timestamp', async ({ filename, ...sample }) => {
    const committed = JSON.parse(await readFile(join(samplesDir, filename), 'utf8'));
    const fresh = buildSampleProject({ filename, ...sample });
    // buildProject() stamps updatedAt with the real current time on every call — the one
    // field that can never byte-for-byte match between a committed file and a fresh build.
    const { updatedAt: _committedUpdatedAt, ...committedRest } = committed;
    const { updatedAt: _freshUpdatedAt, ...freshRest } = fresh;
    expect(committedRest, `docs/examples/interactive-video/${filename} is stale — run "node scripts/generate-interactive-video-samples.mjs" and commit the result`).toEqual(freshRest);
  });
});

describe('Interactive Video sample projects are genuinely valid, importable projects', () => {
  test.each(INTERACTIVE_VIDEO_SAMPLES)('$filename passes validateProject(), the component\'s own validate(), and has zero blocking Preflight issues', async ({ filename }) => {
    const raw = JSON.parse(await readFile(join(samplesDir, filename), 'utf8'));
    const result = validateProject(raw);
    expect(result.valid, result.valid ? '' : result.error).toBe(true);

    const componentResult = interactiveVideo.validate(result.project.config);
    expect(componentResult.valid, JSON.stringify(componentResult.errors)).toBe(true);

    const issues = collectSyncIssues({
      componentId: 'interactive-video',
      schema: interactiveVideo.editorSchema,
      config: result.project.config,
      theme: result.project.theme,
      componentOverrides: result.project.componentOverrides,
      settings: {}
    });
    const blocking = issues.filter(issue => issue.severity === 'blocking');
    expect(blocking, JSON.stringify(blocking.map(issue => issue.explanation))).toEqual([]);
  });
});
